import { Question } from '../types/teamTest';

export const TEAM_TEST_QUESTIONS: Question[] = [
  {
    id: 1,
    question: '고향은 어디인가요?',
    description: '지역 기반으로 연고지를 살펴볼게요',
    answers: [
      { label: '서울', teams: { 'LG': 1, '두산': 1, '키움': 1 } },
      { label: '인천', teams: { 'SSG': 2 } },
      { label: '경기도', teams: { 'KT': 1, 'SSG': 1, '키움': 1 } },
      { label: '충청도', teams: { '한화': 2 } },
      { label: '전라도', teams: { '기아': 2 } },
      { label: '경상도', teams: { '삼성': 1, '롯데': 1, 'NC': 1 } },
    ],
  },
  {
    id: 2,
    question: '야구를 보러 간다면 가장 가까운 구장이 어디인가요?',
    description: '실제로 방문하기 편한 곳도 중요하죠',
    answers: [
      { label: '잠실', teams: { 'LG': 1, '두산': 1 } },
      { label: '고척', teams: { '키움': 2 } },
      { label: '수원', teams: { 'KT': 2 } },
      { label: '대전', teams: { '한화': 2 } },
      { label: '광주', teams: { '기아': 2 } },
      { label: '대구', teams: { '삼성': 2 } },
      { label: '사직', teams: { '롯데': 2 } },
      { label: '창원', teams: { 'NC': 2 } },
      { label: '인천', teams: { 'SSG': 2 } },
    ],
  },
  {
    id: 3,
    question: '가장 먼저 떠오르는 "한국야구하면 생각나는 팀"은?',
    description: '첫 인상도 중요한 인연의 시작이에요',
    answers: [
      { label: '두산', teams: { '두산': 2 } },
      { label: 'LG', teams: { 'LG': 2 } },
      { label: 'SSG', teams: { 'SSG': 2 } },
      { label: 'KT', teams: { 'KT': 2 } },
      { label: 'NC', teams: { 'NC': 2 } },
      { label: '삼성', teams: { '삼성': 2 } },
      { label: '한화', teams: { '한화': 2 } },
      { label: 'KIA', teams: { '기아': 2 } },
      { label: '롯데', teams: { '롯데': 2 } },
    ],
  },
  {
    id: 4,
    question: '당신이 좋아하는 경기 스타일은?',
    description: '야구는 다양한 매력이 있죠',
    answers: [
      { label: '홈런이 팡팡 터지는 타격전', teams: { '두산': 1, '기아': 1, 'SSG': 1 } },
      { label: '투수전처럼 팽팽한 경기', teams: { 'LG': 1, '삼성': 1, 'KT': 1 } },
      { label: '수비 플레이가 깔끔한 경기', teams: { '삼성': 1, 'NC': 1, 'LG': 1 } },
      { label: '빠른 주루와 작전야구', teams: { '키움': 1, '한화': 1, 'KT': 1 } },
    ],
  },
  {
    id: 5,
    question: '다음 기업(브랜드) 중 가장 친숙하거나 긍정적인 이미지를 가진 곳은?',
    description: '모기업에 대한 이미지도 팀 선호도에 영향을 줄 수 있어요',
    answers: [
      { label: '삼성 (Samsung)', teams: { '삼성': 2 } },
      { label: 'LG', teams: { 'LG': 2 } },
      { label: '롯데 (Lotte)', teams: { '롯데': 2 } },
      { label: 'KIA (기아자동차)', teams: { '기아': 2 } },
      { label: '한화 (Hanwha)', teams: { '한화': 2 } },
      { label: 'KT (케이티)', teams: { 'KT': 2 } },
      { label: '신세계 / 이마트 (SSG)', teams: { 'SSG': 2 } },
      { label: 'NC소프트 (NCSOFT)', teams: { 'NC': 2 } },
      { label: '두산 (Doosan)', teams: { '두산': 2 } },
      { label: '키움증권 (Kiwoom)', teams: { '키움': 2 } },
    ],
  },
  {
    id: 6,
    question: '특히 끌리는 선수 스타일은?',
    description: '어떤 선수를 좋아하시나요?',
    answers: [
      { label: '베테랑 리더형', teams: { '두산': 1, 'LG': 1, '삼성': 1 } },
      { label: '루키나 젊은 선수', teams: { 'NC': 1, 'SSG': 1, 'KT': 1 } },
      { label: '장타자', teams: { '기아': 1, '두산': 1, 'SSG': 1 } },
      { label: '철벽 수비형', teams: { '삼성': 1, 'LG': 1, 'NC': 1 } },
      { label: '마운드 장악형 투수', teams: { 'KT': 1, '삼성': 1, 'LG': 1 } },
    ],
  },
  {
    id: 7,
    question: '내가 선호하는 팀 이미지에 가까운 것은?',
    description: '마지막 질문이에요!',
    answers: [
      { label: '전통 강호, 명문팀', teams: { '삼성': 2, 'LG': 2, '두산': 1 } },
      { label: '젊고 도전적인 신흥 강자', teams: { 'SSG': 2, 'NC': 2, 'KT': 1 } },
      { label: '꾸준한 중위권 실속형', teams: { 'LG': 1, 'KT': 1, 'NC': 1 } },
      { label: '약팀이지만 팬심 강한 팀', teams: { '한화': 2, '롯데': 2 } },
      { label: '개성 있고 실험적인 팀', teams: { '키움': 2, 'NC': 1 } },
    ],
  },
];